// This file is automatically generated by Monicon. Do not edit this file directly.
import "@monicon/icon-loader";

declare module "@monicon/icon-loader" {
  export type MoniconIconName = 
	| "ci:arrow-down-up"
	| "ci:building-03"
	| "ci:calendar-event"
	| "ci:chart-pie"
	| "ci:chevron-down"
	| "ci:chevron-left"
	| "ci:chevron-right"
	| "ci:chevron-up"
	| "ci:file-document"
	| "ci:list-checklist"
	| "ci:map"
	| "ci:note-edit"
	| "ci:search-magnifying-glass"
	| "ci:users-group"
	| "ic:baseline-arrow-back-ios-new"
	| "ic:outline-business"
	| "ic:outline-dark-mode"
	| "ic:outline-event"
	| "ic:outline-home"
	| "ic:outline-light-mode"
	| "ic:outline-logout"
	| "ic:outline-settings"
	| "ic:outline-tour"
	| "material-symbols:account-circle-outline"
	| "material-symbols:article-outline"
	| "material-symbols:chevron-right"
	| "material-symbols:delete-outline"
	| "material-symbols:description-outline"
	| "material-symbols:edit-outline"
	| "material-symbols:home-outline-rounded"
	| "material-symbols:list-alt-check-outline"
	| "material-symbols:lock-outline"
	| "material-symbols:privacy-tip-outline"
	| "material-symbols:settings-outline-rounded"
	| "material-symbols:shield-lock-outline"
	| "mdi:account"
	| "mdi:account-edit"
	| "mdi:account-group"
	| "mdi:calendar-multiple"
	| "mdi:calendar-star"
	| "mdi:camera"
	| "mdi:camera-flip"
	| "mdi:card-account-details"
	| "mdi:cash-remove"
	| "mdi:chart-line"
	| "mdi:check-circle"
	| "mdi:check-circle-outline"
	| "mdi:chef-hat"
	| "mdi:clipboard-check"
	| "mdi:clipboard-text"
	| "mdi:close"
	| "mdi:eye"
	| "mdi:eye-off"
	| "mdi:factory"
	| "mdi:file-document-edit"
	| "mdi:form"
	| "mdi:information-outline"
	| "mdi:loading"
	| "mdi:map-marker"
	| "mdi:map-marker-star"
	| "mdi:store"
	| "mdi:store-outline"
	| "mdi:table"
	| "mdi:trending-up";

  export type MoniconProps = {
    /**
     * The name of the icon to render.
     *
     * @example "mdi:home"
     *
     * For TypeScript users, you must check below for more information.
     *
     * @link https://monicon-docs.vercel.app/troubleshooting/typescript
     */
    name: MoniconIconName;
    /**
     * The size of the icon.
     *
     * @default collection's view box size
     */
    size?: number;
    /**
     * The color of the icon.
     *
     * @default "currentColor"
     */
    color?: string;
    /**
     * The stroke width of the icon. This feature is only available for limited icon collections.
     */
    strokeWidth?: number;
  };
}
